language: cpp
compiler: gcc
os: linux
sudo: required
dist: trusty
cache: 
  directories:
  - $HOME/ionomy/ion/src/leveldb
  - $HOME/ionomy/ion/src/secp256k1
before_install:
  - chmod 755 src/leveldb/build_detect_platform
install:
  - sudo apt-get -qq update
  - sudo apt-get install -y build-essential libtool autotools-dev autoconf pkg-config libssl-dev libboost-all-dev libqt5gui5 libqt5core5a libqt5dbus5 qttools5-dev qttools5-dev-tools libprotobuf-dev protobuf-compiler libcrypto++-dev libevent-dev libminiupnpc-dev libgmp-dev
  - sudo add-apt-repository -y ppa:silknetwork/silknetwork
  - sudo apt-get update -y && sudo apt-get install -y libdb4.8-dev libdb4.8++-dev
script:
  - cd src
  - make -f makefile.unix
  - cd ..
  - qmake -qt=qt5 USE_UPNP=-
  - make
